CREATE TABLE IF NOT EXISTS `tokohub`.`app_settings` (
  `key` VARCHAR(100) NOT NULL,
  `value` VARCHAR(500) NOT NULL DEFAULT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
