CREATE TABLE IF NOT EXISTS tokohub.openai_config (
  id INT NOT NULL DEFAULT 1,
  api_base VARCHAR(500) NOT NULL DEFAULT '',
  api_key VARCHAR(500) NOT NULL DEFAULT '',
  deployment_id VARCHAR(100) NOT NULL DEFAULT 'gpt-4o-standard',
  api_version VARCHAR(50) NOT NULL DEFAULT '2024-08-01-preview',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
